#!/bin/python3

import os
import argparse

from templates import *
from utils.read_json import read_json

ROOT_DIR = os.path.dirname(os.readlink(__file__))

def main():
  cli_data = read_json(ROOT_DIR, ".cli.json")
  parser = argparse.ArgumentParser(prog = cli_data["name"], description = cli_data["description"], epilog = cli_data["epilog"])
  for arg in cli_data["params"]:
    parser.add_argument(arg["arg_short"], arg["arg_extended"], help = arg["arg_help"])

  args = parser.parse_args()

  prices_data = read_json(ROOT_DIR, "data", "prices.json")

  if args.nova and args.paciente:
    novas.getMessage(prices_data, args.nova, args.paciente)

  if args.consulta and args.paciente:
    consultas.getMessage(prices_data, args.consulta, args.paciente)

if __name__ == "__main__":
  main()
